public class Constants {
    public static String SERVICE_STATUS_DISPACTHED      = 'Dispatched';
    public static String SERVICE_STATUS_CLOSED          = 'Closed';
    public static String SERVICE_STATUS_CANCELLED       = 'Cancelled';
    public static String SERVICE_STATUS_COMPLETED       = 'Complete';
    public static String SERVICE_STATUS_ASSIGNED        = 'Assigned';
    public static String SERVICE_STATUS_IN_PROGRESS     = 'In Progress';
    public static String SERVICE_STATUS_NEW             = 'New';
    public static String SERVICE_STATUS_ON_SITE         = 'On Site';
    public static String SERVICE_STATUS_CAPTURE_SIGN    = 'Capture Signature';

    public static String PROFILE_NAME_FOR_TECHNICIAN    = 'Field_Service_Mobile';
    public static String PROFILE_NAME_FOR_DISPATCHER    = 'Field_Service_Dispatcher';
    public static String PROFILE_NAME_FOR_ADMIN         = 'Field_Service_Administrator';
    
    public static String CONTRACT_PRICING_RECORD_TYPE_MARKUP_BASED = 'Markup Based';
    public static String USAGE_RECORD_TYPE_STANDARD_USAGE = 'Standard Usage';

    public static String API_OBJECT_NAME_WORK_ORDER     = 'WorkOrder';
    public static String API_OBJECT_NAME_SERVICE        = 'CKSW_BASE__Service__c';

    public static String FIELD_TYPE_DATETIME            = 'DateTime';

    public static String QUEUE_FAILED_EMAIL_PARSING     = 'Failed_Email_Parsing';
    public static String QUEUE_NCR_EMAIL                = 'NCR_Email';
    public static String QUEUE                          = 'Queue';

    public static String EMAIL_LOG_STATUS_ERROR         = 'Error';
    public static String EMAIL_LOG_STATUS_SUCCESS       = 'Success';
    
    public static final String RECORD_TYPE_MASTER_WORK_ORDER                        = 'Master Work Order';
    public static final String RECORD_TYPE_STANDARD_SERVICE_WORK_ORDER              = 'Standard Service';
    
    public static final String SERVICE_APPOINTMENT_DURATION_TYPE_MINUTES            = 'Minutes';
    public static final String SERVICE_APPOINTMENT_DURATION_TYPE_HOURS              = 'Hours';

    public static final String SERVICE_APPOINTMENT_STATUS_IN_PROGRESS               = 'In Progress';
    public static final String SERVICE_APPOINTMENT_STATUS_ASSIGNED                  = 'Assigned';
    
    public static final String WORK_ORDER_STATUS_IN_PROGRESS                        = 'In Progress';
    public static final String WORK_ORDER_STATUS_ASSIGNED                           = 'Assigned';
    public static final String WORK_ORDER_STATUS_COMPLETED                          = 'Complete';
    public static final String WORK_ORDER_STATUS_CLOSED                             = 'Closed';
    public static final String WORK_ORDER_STATUS_CANCELLED                          = 'Cancelled';
    
    public static final String OBJECT_ACCESS_LEVEL                                  = 'Edit';
    
    public static final String PROFILE_NAME_FOR_COMMUNITY_TECHNICIAN                = 'Field_Service_Technician_Community';
    
    public static final String SERVICE_RESOURCE_RESOURCE_TYPE_TECH                  = 'T';
}